# Generated by Django 5.1.1 on 2024-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ip', models.CharField(max_length=15, verbose_name='IP-адрес')),
                ('date', models.CharField(max_length=20, verbose_name='Дата')),
                ('time', models.CharField(max_length=20, verbose_name='Время')),
                ('method', models.CharField(max_length=20, verbose_name='Метод запроса')),
                ('url', models.CharField(max_length=40, verbose_name='URL_запроса')),
                ('answer', models.IntegerField(verbose_name='Код ответа')),
                ('answer_size', models.IntegerField(verbose_name='Размер ответа')),
            ],
            options={
                'verbose_name': 'Результат логгирования',
                'db_table': 'logging',
            },
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
